# All available Hugo versions are listed here: https://gitlab.com/pages/hugo/container_registry
image: registry.gitlab.com/pages/hugo:0.52

variables:
  GIT_SUBMODULE_STRATEGY: recursive

test:
  script:
  #- apt-get install -y rst2html
  #- apk --no-cache add rst2html
  #- pip install Pygments        # for code view, should be replaced with chroma
  - apk --no-cache add py-pip
  - pip install docutils        # for rst2html
  - hugo
  artifacts:
    paths:
    - public
  only:
  - master

pages:
  script:
  #- apt-get install -y rst2html
  #- apk --no-cache add rst2html
  - apk --no-cache add py-pip
  - pip install docutils        # for rst2html
  - pip install Pygments        # for code view
  - hugo -v
  artifacts:
    paths:
    - public
  only:
  - master
