baseURL         = "https://5min.ninja/"
languageCode    = "en-us"
title           = "5min ninja"
theme           = ["igoyak", "detox"]
contentdir      = "content"
publishdir      = "public"
pygmentsStyle    = "monokai"
canonifyurls    = true
highlight       = true

[taxonomies]
  tag           = "tags"
  category      = "categories"
  series        = "series"

[[menu.main]]
name            = "Blog"
weight          = -120
identifier      = "blog"
url             = "/"

[params]
github          = "//github.com/d3rp"
twitter         = "//twitter.com/rojun_itu"
avatar          = "img/running-ninja.jpg"
author          = "Itu Rojunen"
year            = "2022"
disqusShortname = "5min-ninja"

[security.funcs]
getenv          = ['^HUGO_', '^WC_']
[security.exec]
allow = ['^dart-sass-embedded$', '^go$', '^npx$', '^postcss$', '^rst2html.py$']
osEnv = ['(?i)^(PATH|PATHEXT|APPDATA|TMP|TEMP|TERM)$']
