baseURL         = "http://typingducks.com/"
languageCode    = "en-us"
title           = "typing ducks"
theme           = ["igoyak", "detox"]
contentdir      = "content"
publishdir      = "public"
pygmentsStyle    = "monokai"
canonifyurls    = true
highlight       = true

[taxonomies]
  tag           = "tags"
  category      = "categories"
  series        = "series"

[[menu.main]]
name            = "Blog"
weight          = -120
identifier      = "blog"
url             = "/"

[params]
github          = "//github.com/rojun"
twitter         = "//twitter.com/rojun_itu"
avatar          = "img/running-ninja.jpg"
author          = "Gustav Larsson, Joni Turunen, Seyoung Park"
year            = "2018"
disqusShortname = "5min-ninja"
