baseURL         = "https://robot-unicorn.gitlab.io/blog/"
languageCode    = "en-us"
title           = "5min ninja"
theme           = "detox"
contentdir      = "content"
publishdir      = "public"
pygmentsUseClasses = true
canonifyurls    = true
highlight = true

[permalinks]
blog            = "blog/:slug/"

[taxonomies]
  tag           = "tags"
  category      = "categories"
  series        = "series"

[[menu.main]]
name            = "Blog"
weight          = -120
identifier      = "blog"
url             = "/blog/"

[params]
github          = "//github.com/rojun"
twitter         = "//twitter.com/rojun_itu"
avatar          = "img/running-ninja.jpg"
