baseURL         = "https://rojun.gitlab.io/hugo-blog"
languageCode    = "en-us"
title           = "5 min ninja"
theme           = "cocoa"
contentdir      = "content"
pygmentsuseclasses = true

[permalinks]
blog            = "blog/:slug/"

[taxonomies]
  tag           = "tags"
  category      = "categories"
  series        = "series"

[[menu.main]]
name            = "Blog"
weight          = -120
identifier      = "blog"
url             = "/blog/"

[params]
github          = "//github.com/rojun"
twitter         = "//twitter.com/rojun_itu"
avatar          = "img/joni_hiihtaa.jpg"
