baseURL         = "https://robot-unicorn.gitlab.io"
languageCode    = "en-us"
title           = "5min ninja"
theme           = "cocoa"
contentdir      = "content"
publishdir      = "public"
#pygmentsUseClasses = true
pygmentsStyle    = "monokai"
canonifyurls    = true
highlight       = true

#[permalinks]
#blog            = "blog/:slug/"

[taxonomies]
  tag           = "tags"
  category      = "categories"
  series        = "series"

[[menu.main]]
name            = "Blog"
weight          = -120
identifier      = "blog"
url             = "/"

[params]
github          = "//github.com/rojun"
twitter         = "//twitter.com/rojun_itu"
avatar          = "img/running-ninja.jpg"
