baseURL         = "https://5min.ninja/"
languageCode    = "en-us"
title           = "5min ninja"
theme           = ["igoyak", "detox"]
contentdir      = "content"
publishdir      = "public"
pygmentsStyle    = "monokai"
canonifyURLs    = true
highlight       = true

[taxonomies]
tag           = "tags"
category      = "categories"
series        = "series"

#[[menu.main]]
#name            = "Blog"
#weight          = -40
#identifier      = "blog"
#url             = "/blog/"
[[menu.main]]
name            = "About"
weight          = 20
identifier      = "about"
url             = "/about"

[params]
github          = "d3rp"
twitter         = "twitter.com/rojun_itu"
avatar          = "img/running-ninja.jpg"
author          = "Itu Rojunen"
year            = "2023"

[security.funcs]
getenv          = ['^HUGO_', '^WC_']
[security.exec]
allow = ['^dart-sass-embedded$', '^go$', '^npx$', '^postcss$', '^rst2html$']
osEnv = ['(?i)^(PATH|PATHEXT|APPDATA|TMP|TEMP|TERM)$']
